from pathlib import Path


def main() -> None:
    project_root = (
        Path(__file__)
        .resolve()
        .parents[3]
    )

    output_directory = (
        project_root
        / "data"
        / "knowledge_base"
        / "wazuh"
    )

    output_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    output_path = (
        output_directory
        / "wazuh_soc_reference.md"
    )

    sections = [
        {
            "id": "log-data-analysis",
            "title": "Log Data Analysis",
            "url": (
                "https://documentation.wazuh.com/"
                "current/user-manual/capabilities/"
                "log-data-collection/"
                "log-data-analysis.html"
            ),
            "content": """
Wazuh analyzes security log data through three main
processing phases: pre-decoding, decoding, and rule matching.

During pre-decoding, the analysis engine extracts general
information from syslog-like headers, such as timestamps,
hostnames, and program names.

During decoding, Wazuh uses decoders to parse log messages
and extract structured security-relevant fields.

During rule matching, decoded events are compared against
the Wazuh ruleset. Matching rules can generate security
alerts for further investigation by SOC analysts.
""",
        },
        {
            "id": "alert-management",
            "title": "Alert Management",
            "url": (
                "https://documentation.wazuh.com/"
                "current/user-manual/manager/"
                "alert-management.html"
            ),
            "content": """
Wazuh alerts are generated by the Wazuh manager after
processing events received from monitored endpoints and
agentless devices.

Generated alerts are stored on the Wazuh server in:

/var/ossec/logs/alerts/alerts.log

and:

/var/ossec/logs/alerts/alerts.json

Wazuh assigns severity levels to events according to the
rules that match those events.

The default alert threshold causes events at the configured
minimum severity level and above to be recorded as alerts.
""",
        },
        {
            "id": "log-collection",
            "title": "Log Data Collection",
            "url": (
                "https://documentation.wazuh.com/"
                "current/user-manual/capabilities/"
                "log-data-collection/how-it-works.html"
            ),
            "content": """
The Wazuh Logcollector module collects logs from monitored
endpoints, applications, and network devices.

Collected logs are forwarded to the Wazuh server where they
are analyzed in real time using decoders and rules.

Decoders extract relevant information and map log data to
structured fields.

The Wazuh analysis engine evaluates decoded events against
rules and generates alerts when rule conditions are met.

Wazuh can also receive syslog messages from devices where
a Wazuh agent cannot be installed.
""",
        },
        {
            "id": "decoders",
            "title": "Wazuh Decoders",
            "url": (
                "https://documentation.wazuh.com/"
                "current/user-manual/ruleset/"
                "decoders/index.html"
            ),
            "content": """
Wazuh decoders extract information from received log
messages and transform raw log information into structured
fields that can be analyzed by the ruleset.

Decoding occurs after the pre-decoding phase.

Wazuh includes decoders for multiple common log formats and
also allows users to create custom decoders.

Custom decoders are useful when an application or security
tool produces a log format that is not handled correctly by
the default Wazuh ruleset.
""",
        },
        {
            "id": "custom-decoders",
            "title": "Custom Decoders",
            "url": (
                "https://documentation.wazuh.com/"
                "current/user-manual/ruleset/"
                "decoders/custom.html"
            ),
            "content": """
Custom Wazuh decoders can be used to parse application or
security logs that require environment-specific processing.

Small custom decoder configurations can be placed in:

/var/ossec/etc/decoders/local_decoder.xml

For larger customizations, separate decoder files can be
created under:

/var/ossec/etc/decoders/

Custom decoder changes should be kept outside the default
ruleset directories so that local modifications are not
lost during Wazuh upgrades.
""",
        },
        {
            "id": "custom-rules",
            "title": "Custom Rules",
            "url": (
                "https://documentation.wazuh.com/"
                "current/user-manual/ruleset/"
                "rules/custom.html"
            ),
            "content": """
Wazuh custom rules allow security teams to define detection
conditions that are specific to their applications,
environment, and security requirements.

Wazuh recommends using rule identifiers between 100000 and
120000 for custom rules to avoid conflicts with built-in
rules.

Small rule customizations can be stored in:

/var/ossec/etc/rules/local_rules.xml

Larger custom rulesets can be stored as separate files in:

/var/ossec/etc/rules/

The wazuh-logtest utility can be used to test decoding and
rule matching before rules are deployed.
""",
        },
        {
            "id": "rules-syntax",
            "title": "Rules and Detection Logic",
            "url": (
                "https://documentation.wazuh.com/"
                "current/user-manual/ruleset/"
                "ruleset-xml-syntax/rules.html"
            ),
            "content": """
The Wazuh ruleset analyzes incoming decoded events.

A rule generates an alert when its configured conditions
are satisfied.

Rule conditions can use elements such as match, regex,
decoded_as, and category to identify security-relevant
events.

Rules can therefore transform normalized log events into
security detections that can be investigated by a SOC.
""",
        },
        {
            "id": "decoder-syntax",
            "title": "Decoder Processing",
            "url": (
                "https://documentation.wazuh.com/"
                "current/user-manual/ruleset/"
                "ruleset-xml-syntax/decoders.html"
            ),
            "content": """
Wazuh decoders separate received events into structured
information before rule evaluation.

The wazuh-logtest utility can be used to test an event and
inspect the pre-decoding, decoding, and rule-matching
results.

This is useful when developing or troubleshooting custom
SOC detection logic.
""",
        },
        {
            "id": "rule-severity",
            "title": "Rule Severity Classification",
            "url": (
                "https://documentation.wazuh.com/"
                "current/user-manual/ruleset/"
                "rules/rules-classification.html"
            ),
            "content": """
Wazuh rules use severity levels to indicate the importance
of detected events.

Rule levels range from low-value or ignored events to
high-severity security events.

The severity associated with a matching rule helps SOC
analysts prioritize alerts and determine which events
require investigation or response.
""",
        },
    ]

    lines = [
        "# Wazuh SOC Knowledge Reference",
        "",
        "**Source:** Official Wazuh documentation",
        "**Documentation branch:** current",
        "**Purpose:** SOC alert analysis and RAG retrieval",
        "",
        (
            "This knowledge-base document contains a curated "
            "technical reference derived from the official "
            "Wazuh documentation for use by the AI-Powered "
            "SOC Analyst."
        ),
        "",
    ]

    for section in sections:
        lines.extend(
            [
                (
                    "## WAZUH-"
                    + section["id"]
                    + " - "
                    + section["title"]
                ),
                "",
                (
                    "**Wazuh Topic ID:** WAZUH-"
                    + section["id"]
                ),
                (
                    "**Topic:** "
                    + section["title"]
                ),
                (
                    "**Official Source:** "
                    + section["url"]
                ),
                "",
                "### SOC Reference",
                "",
                section["content"].strip(),
                "",
            ]
        )

    output_path.write_text(
        "\n".join(lines).strip()
        + "\n",
        encoding="utf-8",
    )

    print(
        "Wazuh knowledge base generated: OK"
    )
    print(
        "Output:",
        output_path,
    )
    print(
        "Topics generated:",
        len(sections),
    )
    print(
        "Size:",
        output_path.stat().st_size,
        "bytes",
    )


if __name__ == "__main__":
    main()
