"""add ML anomaly fields to SOC reports

Revision ID: 1d64568aa57c
Revises: 81068beebb37
Create Date: 2026-08-31 11:08:05.470269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d64568aa57c'
down_revision: Union[str, Sequence[str], None] = '81068beebb37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soc_reports', sa.Column('ml_engine', sa.String(length=50), nullable=True))
    op.add_column('soc_reports', sa.Column('ml_is_anomaly', sa.Boolean(), nullable=True))
    op.add_column('soc_reports', sa.Column('ml_anomaly_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soc_reports', 'ml_anomaly_score')
    op.drop_column('soc_reports', 'ml_is_anomaly')
    op.drop_column('soc_reports', 'ml_engine')
    # ### end Alembic commands ###
