"""add SOAR action audit logs

Revision ID: 81068beebb37
Revises: 2d87f685e2ec
Create Date: 2026-08-31 04:39:57.473380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81068beebb37'
down_revision: Union[str, Sequence[str], None] = '2d87f685e2ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soar_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['soar_actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soar_action_logs_action_id'), 'soar_action_logs', ['action_id'], unique=False)
    op.create_index(op.f('ix_soar_action_logs_id'), 'soar_action_logs', ['id'], unique=False)
    op.create_index(op.f('ix_soar_action_logs_incident_id'), 'soar_action_logs', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soar_action_logs_incident_id'), table_name='soar_action_logs')
    op.drop_index(op.f('ix_soar_action_logs_id'), table_name='soar_action_logs')
    op.drop_index(op.f('ix_soar_action_logs_action_id'), table_name='soar_action_logs')
    op.drop_table('soar_action_logs')
    # ### end Alembic commands ###
