"""add incident operational timestamps

Revision ID: ae4352e0ddab
Revises: 1d64568aa57c
Create Date: 2026-09-02 13:31:40.642670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae4352e0ddab'
down_revision: Union[str, Sequence[str], None] = '1d64568aa57c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "incidents",
        sa.Column(
            "event_timestamp",
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.add_column(
        "incidents",
        sa.Column(
            "detected_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text(
                "CURRENT_TIMESTAMP"
            ),
        ),
    )

    op.add_column(
        "incidents",
        sa.Column(
            "resolved_at",
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.alter_column(
        "incidents",
        "detected_at",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'resolved_at')
    op.drop_column('incidents', 'detected_at')
    op.drop_column('incidents', 'event_timestamp')
    # ### end Alembic commands ###
