"""add workflow thread id to incidents

Revision ID: ba510f3af2c9
Revises: f012ddf3cf65
Create Date: 2026-09-12 01:09:34.099542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba510f3af2c9'
down_revision: Union[str, Sequence[str], None] = 'f012ddf3cf65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('workflow_thread_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_incidents_workflow_thread_id'), 'incidents', ['workflow_thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_workflow_thread_id'), table_name='incidents')
    op.drop_column('incidents', 'workflow_thread_id')
    # ### end Alembic commands ###
