"""add incident disposition

Revision ID: f2c7d6ef5ae6
Revises: ae4352e0ddab
Create Date: 2026-09-02 15:29:19.361968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c7d6ef5ae6'
down_revision: Union[str, Sequence[str], None] = 'ae4352e0ddab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "incidents",
        sa.Column(
            "disposition",
            sa.String(length=50),
            nullable=False,
            server_default="unknown",
        ),
    )

    op.alter_column(
        "incidents",
        "disposition",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'disposition')
    # ### end Alembic commands ###
